name: MSYS2

on: [push, pull_request]

jobs:
  msys2-ucrt64:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v5

      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-pkcs11-helper
            mingw-w64-ucrt-x86_64-libassuan
            mingw-w64-ucrt-x86_64-libgcrypt
            mingw-w64-ucrt-x86_64-gcc
            man2html
            autoconf
            automake
            pkgconf
            make
            libtool
            m4
      - name: Debug environment
        run: |
          autoconf --version
          automake --version
          aclocal --version
          bash --version
          pacman -Q autoconf automake m4 pkgconf

      - name: Generate
        run: autoreconf -ivf

      - name: Configure
        run: ./configure --enable-strict --enable-pedantic

      - name: Build
        run: make -j$(nproc)

      - name: Build
        run: |
          cp /ucrt64/bin/{libassuan-0.dll,libgpg-error-0.dll,libgcrypt-20.dll,libcrypto-3-x64.dll,libpkcs11-helper-1.dll,zlib1.dll} gnupg-pkcs11-scd/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gnupg-pkcs11-scd-ucrt64
          path: |
            gnupg-pkcs11-scd/gnupg-pkcs11-scd.*
            gnupg-pkcs11-scd/*.dll
